### ISSUE TITLE
datepicker

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#11]
potrebujeme datepicker (ten v material-ui me prijde moc intrusivni - vybleje se doprostred)

Nasel jsem tyto dva:
http://jquense.github.io/react-widgets/docs/#/dropdownlist
http://eonasdan.github.io/bootstrap-datetimepicker/

protoze budu po tobe chtit stylovani do material design, tak asi vyber ty, ktery pujde lepe stylovat. 
Nebo najdi nejakej jinej.

 Dale potrebujeme:
- volitelnou podporu time  (mame policka date a policka datetime, takze potrebujeme datepicker a datetimepicker , obe komponenty vyse to umi)
- lokalizaci
- validaci formatu dle lokalizace

Chovat se to ma tak ze pri najeti do policka se to nerozbali, clovek normalne pise datum, teprve pri kliknuti na ikonu se rozbali popup.

Vypadat to muze nejak takto:

![image](https://cloud.githubusercontent.com/assets/1957955/10305535/ea9bfe84-6c20-11e5-8455-18ad5207ad4d.png)

![image](https://cloud.githubusercontent.com/assets/1957955/10305542/f56d8094-6c20-11e5-8bc1-c6eb5cb5ebe1.png)

Jinak ta prvni knihovna ma take pekny dropdown. Mozna ho pouzijeme vedle react-select pro dropdowny ktere maji malo polozek - tam me prijde jeho chovani (rozbaleni kdyz do nej kliknu) lepsi nez react-select kde po najeti  do nej pises search .... ale to nema prioritu a je otazka jestli to pujde stylovat na material...

**Comment by jzelenka** [comment]
Pro testovani si ho pridej treba na stranku invoiceList (tam ted nic neni)

**Comment by martinnemec3** [comment]
Ten prvni vypada lepe asi, zkusim to s nim. Pridam tedy 'react-widgets' do dependencies.

**Comment by jzelenka** [comment]
jo jo,
udelej prosim npm run build  predtim a potom a podivej se na 2 js soubory v build adresari - o kolik se zvetsi.

**Comment by martinnemec3** [comment]
zvetsil se pouze ten module-*.js o 83 bajtu.

**Comment by jzelenka** [comment]
to je nejak malo...
ono to asi bude vic az udelas nejaky import...

**Comment by martinnemec3** [comment]
Jinak ve webpack.config chybel loader na .gif soubory, tak jsem tam k tomu file-loaderu pripsal "gif" (ttf|eot|svg|gif).

**Comment by martinnemec3** [comment]
Dame datepickeru nejakou pevnou sirku?

**Comment by jzelenka** [comment]
gif - ok,
pevnou sirku - zatim ne.


2015-10-07 9:12 GMT+02:00 martinnemec3 <notifications@github.com>:

**Comment by martinnemec3** [comment]
Jak by mel datepicker vypadat v pripade, ze bude obsahovat vyber data i casu? Budou tam dve ikonky (kalendar a hodiny)? Nebo nejaky jiny zpusob?

**Comment by jzelenka** [comment]
to je jedno.... ono to bude dost vzacne.  Vetsinou bude pouze datum.

**Comment by jzelenka** [comment]
Jake ma ten datepicker npm dependency?

Asi pridam pro praci s datumy (parsovani, formatovani, lokalizace..) knihovnu moment.js

Pouziv ji? nebo neco jineho?

**Comment by jzelenka** [comment]
musime sledovat velikost....

**Comment by martinnemec3** [comment]
"dependencies": {
    "classnames": "^2.1.2",
    "date-arithmetic": "^3.0.0",
    "dom-helpers": "^1.3.2",
    "globalize": "~0.1.1",
    "gulp-babel-helpers": "^2.2.2",
    "uncontrollable": "^1.4.0"
  }

**Comment by martinnemec3** [comment]
Datepicker je nastylovan do material-ui. Defaultne jsem mu nastavil pouze datum, cas se necha pomoci property zvolit. Zatim je pridan na strance invoiceList na vyzkouseni.
M.

**Comment by jzelenka** [comment]
vypada to dobre...

stran velikosti, je tam narust 184kb -> 269kb

ma to celkem podivne zavislosti jako treba gulp-babel-helpers - to by mel byt spise dev nez runtime dependdency.....

zauzoo@1.0.0 C:\projekty\work\zauzoo\fe
└─┬ react-widgets@2.8.2
  ├── date-arithmetic@3.0.1
  ├── globalize@0.1.1
  └─┬ gulp-babel-helpers@2.2.2
    ├── babel-plugin-external-helpers@1.1.1
    ├─┬ gulp-babel@5.2.1
    │ ├── replace-ext@0.0.1
    │ ├── through2@2.0.0
    │ └── vinyl-sourcemaps-apply@0.1.4
    ├─┬ gulp-util@3.0.6
    │ ├── array-differ@1.0.0
    │ ├── beeper@1.1.0
    │ ├── dateformat@1.0.11
    │ ├── lodash._reescape@3.0.0
    │ ├── lodash._reevaluate@3.0.0
    │ ├── lodash._reinterpolate@3.0.0
    │ ├─┬ lodash.template@3.6.2
    │ │ ├── lodash._basetostring@3.0.1
    │ │ ├── lodash._basevalues@3.0.0
    │ │ ├── lodash.escape@3.0.0
    │ │ └── lodash.templatesettings@3.1.0
    │ ├─┬ multipipe@0.1.2
    │ │ └── duplexer2@0.0.2
    │ ├── through2@2.0.0
    │ └─┬ vinyl@0.5.3
    │   └── clone-stats@0.0.1
    └── through2@0.6.5

 ... casem se na to podivame, otevru na to bug.

**Comment by jzelenka** [comment]
FYI - pridal jsem moment.js
taky s tim byl problem - viz https://github.com/zauzoo/fe/wiki/moment.js
