### ISSUE TITLE
react-select pokud je multi, nema modre podtrzitko

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#13]
U "multi" selectu nefunguje modre podtrzeni (podtrzitko zustava sede). Je to proto, ze se value renderer spousti pro kazdou z tech zadanejch hodnot zvlast, takze by to vedlo na hodne ohybani a hodne.

**Comment by martinnemec3** [comment]
Toto by melo byt doplneni s druhym uzavrenim issue 8.
