### ISSUE TITLE
oznacovani radku v show selection

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#15]
- prestalo fungovat oznaceni radku pri kliknuti kamkoliv na radek. musi se pouze do zaskrtavaciho policka

**Comment by jzelenka** [comment]
To jsem udelal schalne (predtim to tam udelal takhle Martin)
gmail to ma taky jen na zaskr. policku a na radku jsou hyperlinky co chodi na detaily.....

**Comment by jzelenka** [comment]
jestli ses silne proti tak dej reopen.
