### ISSUE TITLE
sirka headeru v gridu

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#17]
Prece jenom potrebujeme dat nejaky buffer k delce sloupce vzhledem k jeho headeru, protoze potrebujeme aby vzdy byla moznost kliknout na filtr (ikonka co se objevi na hover). Kdyz si das Vehicle grid a trochu ho zuzis tak u Vehicle Type se na to skoro neda kliknout....

Je jedno jak to udelas - jestli neco pridas k sirce nebo nejak jinak...

Taky kdyz je ten sloupec setrideny - ma sipku - tak by na filtr melo jit kliknout...

**Comment by martinnemec3** [comment]
Takze pro vypocet minimalni sirky pricitat k headeru rekneme 2 nebo 3 pismena?

**Comment by jzelenka** [comment]
no tak akorat aby se ten filtr vesel... :)

**Comment by milant007** [comment]
k tomu mam jeste ja z testovani: 
- kdyz zuzite prohlizec, nebo z telefonu, tak ten filtr neni nikde kde nazev sloupce = sirka sloupce

**Comment by jzelenka** [comment]
no vzdyt presne o tom ten bug je...

**Comment by martinnemec3** [comment]
Pridal jsem k textu headeru sekvenci 'AA' (mela by zarucit dostatecnou sirku pro sipku - razeni a trychtyr - filtrovani). M.
