### ISSUE TITLE
NumberField

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#19]
Number field by byl zalozeny na  MUI TextFieldu + by mel tuto funkcnost:

- pri onFocus se zrusi formatovani
- pri onBlur se zformatuje
- format se specifikuje

Slo by pouzit, respektive inspirovat se 
https://github.com/hongymagic/react-number-input

je to vlastne jen jeden soubor
https://github.com/hongymagic/react-number-input/blob/master/src/react-number-input.js

takze mam predstavu ze:
a) udelas obalovou komponentu kolem textFieldu kam pridas tuto funkcnost
nebo
b) forknes MUI respektive jen asi vykousnes TextField a pridas to rovnou do nej.....

prijde me to jednodussi nez se snazit duplikovat textField kolem teto komponenty

Dependency:
numeral.js  - to je OK, tu si pridame do zauzoo, bude to nase knihovna pro praci s cisly (jako mame moment.js pro datumy)
object-assign - tenhle shim nepotrebujeme, pro nase prostredi (Chrome + babel) funguje build-in Object.assign()

Na tom projektu zminuji ze maji ruzne verze pro react 0.13, 0.14.  My zatim pouzivame 0.13 a na 0.14 budeme upgradovat az vsechny dependency zupgraduji, coz muze jeste chvili trvat a nebude to pain-less (napr. react-router bude zrejme podporovat react 0.14 pouze ve verzi 1.0, ktera ma nekompatibilni api se soucasnou 0.13.3 -> pracny upgrade zauzoo....)

Tak se mozna podivej jak se to lisi a zatim pouzij react-number-input@1.13 a mej nekde v patrnosti ze budeme casem upgradovat.

### Validace
(podobne bude platit pro datepicker)

pri chybnem formatu by se policko melo oznacit jako chybne - jako textField s chybou, tj. setnout errorText

react-number-input funguje jako nas datepicker - pri onBlur chybna hodnota zmizi.

Ja zatim nevim jak presne budu resit validace formularu, jestli bude stacit validace na onBlur (provede se onBlur kdyz submitnu form ENTERem z toho policka?).
Tedy jestli muze byt validace formatu pouze na onBlur a tedy zapouzdrena v te kompomente

Mozna by tam mohla byt nejaka metoda validate(), ktera by se provedla na onBlur ale mohl by si ji clovek zavolat i sam...

Jeste, react-number-input pri zadani vetsiho poctu desetinnych mist nez specifikovano ve formatu, provede zaokrouhleni - my se muzeme chovat ze je to chyba formatu, pokud je to jednodussi, nevim, prijde me nebezpecne menit hodnotu co zadal uzivatel....

**Comment by martinnemec3** [comment]
NumberField je pripravenej.

**Comment by martinnemec3** [comment]
Jeste jedna vec - ten error text v pripade chybneho zadani ma byt nejakej generic? Resp. odkud ho mam brat? Mam na to udelat property?
M.

**Comment by jzelenka** [comment]
No jasne, preci `errorText` jako je na TextFieldu

**Comment by martinnemec3** [comment]
JJ, ale tam se chova tak, ze pokud je vyplnen, je zobrazen, pokud je prazdnej, zobrazen neni. Myslel jsem ze errorText nechame vyhrazeno aby se chovalo stejne jako u textfieldu (pro zobrazovani chyb ze serveru)

**Comment by jzelenka** [comment]
volal jsem....

**Comment by jzelenka** [comment]
zaviram, mame nas obalenej TextField - NumberField
