### ISSUE TITLE
velikost policek formulare - TextField a StyledSelect

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#24]
Na detailu zakaznika
http://zauzoo.com/party/detail/1
nebo
http://zauzoo.com/party/detail/new?partyCategory=PO

se pri pouziti `StyledSelect` ukazuji problemy:

- nefunguje `floatingLabelText` property (funguje jen jako `placeholder`, nelita nahoru, kdyz je vyplneno). Mel by fungovat stejne jako u TextFieldu, tj. vyletet nahoru kdyz je pole vyplnene nebo kdyz dostane focus.
- po zmenseni textu na 14 je u `searchable` StyledSelectu (Searchable davam, kdyz je pocet polozek vetsi nez 8, zde pouze `defaultCurrency`) prompt moc vysoko
- searchable prompt je taky zbytecne daleko od leveho kraje 
- rozbalovaci sipecka je moc daleko od praveho kraje a zrejme je taky odsazena v px, takze kdyz se pole zmensuje tak zajede klidne pres pulku. Kdyz bude vic u kraje tak asi muze zustat odsazena absolutne, nebo muze byt odsazena v %

Pro obe kompomenty - `TextField` a `StyledSelect` a taky `StyledDatepicker` a `NumberInput`, ktere jsem jeste nezkousel - potrebuju mit moznost zmensit radek. A potrebuju to delat pro `TextField` a pro ty nase (`StyledSelect`, `StyledDatepicker`, `NumberInput`) **stejne**. 
To znamena, protoze `TextField` neni nas, ze to musi jit pres `style` prop (pripadne plus dalsi style-like props TextFieldu:  errorStyle, floatingLabelStyle, hintStyle, inputStyle, underlineStyle, underlineFocusStyle, underlineDisabledStyle)

Potreboval bych tedy pripravit rekneme dve nastaveni techto style props:  "mensi" a "jeste mensi".
Budeme mit tedy celkem 3 velikosti (velka - default soucasna, mensi, jeste mensi).

Pisu to takhle protoze predpokladam, ze nepujde menit velikost libovolne (napriklad kdyz se zmensi `height` TextFieldu, tak se rozbije umisteni floating labelu atd. ). Ani bootstrap to nema libovolne, ale ma asi 3 prednastavane, neni to ani potreba.

<br/><br/>

Jeste jak to mam delane, abys to mohl zkouset:
- na `partyPoForm.js` vidis, ze jednolive kompomenty maji jen jednu spreadovanou prop: 
```html
          <TextField {...ico} />
```
- ta je vytvorena pomoci HOC funkce `createForm`, ktera pro to bere data z ruznych zdroju: definition objekt, mdField (serverova konfigurace) ... vse viz `createForm.js`
- proto potrebuju aby vsechny fieldove komponenty mely stejny "interface", tedy props. Samozrejme nektere jich maji vic, ale proste ty spolecne se musi stejne jmenovat....
- pokud potrebuju nejakou overridnout, tak muzu, treba fullWidth, takto:

```html
          <TextField {...ico} fullWidth={false} />
```
-  pro `style` prop to plati stejne, ale navic, protoze ji muzu chtit mergovat spise nez overridovat, tak muzu dat style prop na definition objekt a tato pak bude mergovana do te co je natvrdo v `createForm.js`. Takze treba ico ma vysledny style:
```js
         {
            fontSize: 14,
            fontWeight: 'bold'
         }
```
Samozrejme umistenim `style` primo na komponentu bych overridnul ten `fontSize: 14` ...

Kdyz tak se ozvi :)

**Comment by martinnemec3** [comment]
StyledSelect jsem upravil, aby se zobrazoval nejak rozumne, tak na to koukni... k tomu spolecnymu interface asi budu potrebovat do budoucna seznam vsech properties, ktery chces takto pouzivat (nejaky jsou implementovany, jiny se dodelaji asi pri pozadavku na ne).

**Comment by jzelenka** [comment]
mam cekat na PR, nebo si to vyzkouset z branche?

**Comment by martinnemec3** [comment]
Udelal jsem teda PR

**Comment by jzelenka** [comment]
Na novem formulari je to dobre, ale kdyz si otevres detail existujiciho zakaznika, tak floating labely nejsou zvednute.

**Comment by martinnemec3** [comment]
Opraveno

**Comment by jzelenka** [comment]
Super,

To zmenseni rakdu se provede zadanim height na to policko, ze?
Zkusil jsem dat na StyledSelect 50px a krasne to zafungovalo....

Ale bohuzel ne na obycejnem textFieldu, poradis jak nastavit vsechny ty jeho style-like property?

**Comment by martinnemec3** [comment]
No, neni to moc jednoduchy, ten element je slusna skladacka... ty chces teda ted udelat nizsi? U textField je jeden velkej problem - ten ze vyska se vypocitava nekde pri renderingu a nastavuje se podle toho zda tam mas treba ten floatingLabel nebo ne na 48px pripadne na 72px. Bojim se ze mensi to neudelat, pokud bys to chtel vetsi, asi bych pouzil min-height.

**Comment by martinnemec3** [comment]
Styly pro ruzne velikosti TextFieldu:
* Standardni velikost
   * U te se nic nemeni
* Mala velikost
   * S floatingLabelem: style={{height: '54px', fontSize: '14px'}} hintStyle={{lineHeight: '24px'}} floatingLabelStyle={{marginBottom: '0px', top: 'initial', bottom: '12px'}} inputStyle={{marginTop: '0px', paddingTop: '6px'}}
   * bez floatingLabelu: style={{height: '36px', fontSize: '14px'}} hintStyle={{lineHeight: '24px'}} inputStyle={{marginTop: '0px', paddingBottom: '10px'}}

U StyledSelectu by melo stacit jen style={{height: '54px/36px', fontSize: '14px'}}
