### ISSUE TITLE
floating label u StyledDatePicker

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#26]
`StyledDatePicker` by mel mit floating label jako treba TextField. Nyni ma pouze property `placeholder` a to se chova jako placeholder, nikoliv jako floating label.

Property by se idealne jmenovalo stejne jako u TextFieldu - `floatingLabelText`

**Comment by martinnemec3** [comment]
Vyladil jsem to, ze ted na strance party - detail pri editaci udaju to vypada pekne. Dam PR.

**Comment by jzelenka** [comment]
super,
diky
