### ISSUE TITLE
Cancel editacniho okna

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#29]
kdyz omylem zmenim neco behem editace, nebo v kontaktech adresach rolich omylem kliknu na PLUS, tak se neda dost dobre vratit zpet, musim vyplnit required fields, pak muzu potvrdit pres zelene zaskrtavadlo a pak zase smazat pres krizek.
takze by se asi hodilo nejake tlacitko Cancel vedle toho zeleneho zaskrtavadla.

**Comment by jzelenka** [comment]
jo, to je ve fronte... + jeste aby tlacitko Save bylo disablovane do prvniho editu - aby se tak poznalo ze uz bylo editovano.

Ono to spolu souvisi.

**Comment by jzelenka** [comment]
hotovo
