### ISSUE TITLE
grid - horizontalni scrolovani

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#3]
Horizontalni scrollovani gridu nefunguje dobre.

jedna se o gridComp.js a gridComp.less

- Vertikalni scrolling je OK
- jednotlive sloupce (bunky) maji width v %, ktera je predpocitana na zaklade obsahu sloupcu (delky stringu, tj. je to trochu odhad)
- situace je komplikovana pouzitim virtualniho scrollingu (VirtualList.js) pro grid body
- asi bude nutne obalit grid header (div.md-grid-header) a grid body (div.md-grid-body) do divu, aby se cely grid posouval najednou, jenze to rozbije roztazeni gridu na 100% vysky okna, ktere je udelane pres flexbox, takze je netrivialni :)

fungovani stavi v aktualni CH a FF.

**Comment by martinnemec3** [comment]
Issue vyreseno v branchi (issue#3).
* horizontalni scrolling jiz funguje - posun headeru je resen pomoci odchyveni udalosti scroll (virtualList.js#onScroll())
* minimalni sirka sloupcu (min-width) se nastavuje jako minimum z hodnot:
   * MAXIMAL_COLUMN_MIN_WIDTH_PX (definovano v gridService.js#computeGridWidths())
   * sirky retezce slozeneho z **n** znaku *PATTERN_LETTER* (definovaneho v gridService.js#computeGridWidths()), kde **n** je pocet znaku nejdelsiho textu ve sloupci

**Comment by jzelenka** [comment]
nejak jsem doprasil ten header padding pri zarovnani vlevo a on/off scrollbaru. Je to v masteru.

**Comment by martinnemec3** [comment]
Supr to funguje. Koukam ze to mas volany na search(), takze pri resizu se to neprepocita, ale asi neni moc motivace aby to umelo.

**Comment by jzelenka** [comment]
Tak jsem to pridal i na resize
