### ISSUE TITLE
Tlacitko New a Copy ve formulari

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#30]
Mozna to mas taky v planu, ale pro jistotu:
- pridat tlacitko novy i ve formulari(nyni je pouze v gridu)
- pridat tlacitko copy ve formulari. simuluje to kliknuti na novy a vyplneni poli stejne jake byly v puvodnim formulari. Samozrejme neulozi, protoze by to mohlo vyhnit na duplicitach a preci jen neco uzivatel zmeni nez to ulozi. Tato funkce se hlavne vyuzije u FA, ty se kopiruji hodne(vcetne polozek) nebo napr u karet zbozi u obchodniho modelu kde temer totozne zbozi se vyplati vyhledat zkopirovat, pak zmenit jen cislo a nazev, ale vse ostatni uz je natazene a pouze se ulozi. 
- a jeste jsem si vzpomnel listovani mezi zaznamy, pokud neco hledam v detailu, tak abych nemusel pokazde skakat zpet do gridu ale pouze pouzival sipku vpred nebo vzad

nema to prioritu, novy jde alespon z gridu a kopirovani ve Volvu neni aktualni

**Comment by jzelenka** [comment]
tlacito novy a copy ve formulari (tj. nyni party a user) je hotove.
Copy zkopiruje formulove seznamy, ale ne gridove - tj. na party se zkopiruji role, kontakty a adresy, ale ne auta, faktury a vazby.

Co se tyce listovani mezi zaznamy - co by tvorilo ten list?  Aktualni search v gridu ze ktereho byl formular otevren?

**Comment by milant007** [comment]
JJ, to je jasny, ze grid to nezkopiruje. Jen u zakazek(FA, dodaky, atd. to bude chtit, aby to kopirovaly i polozky). Trebas pro generovani dobropisu je to dulezity, protoze najdes FA, tu zkopirujes a das generuj dobropis.

Listovani mezi zaznamy podle aktualne zafitrovaneho a sesortovaneho gridu. V MD to nefunguje a je to horor. Zafiltrujes si, setridis podle vybraneho sloupce a pak prochazis, protoze neco hledas(trebas v navazanych gridech) porovnavas, nebo upravujes zaznamy a ono to skace "nahodne" mezi zaznamy.

**Comment by jzelenka** [comment]
Jasne u faktur to bude kopirovat i polozky, to je jasny.

Listovani mezi zaznamy je hotove. Bylo to pomerne slozite.
Funguje to pouze na page-level (ne na subgridech na detailu) gridech a pouze kdyz jdes na hlavni entitu gridu - napr. na Customers muzes jit taky na party Sales R. name - pak to nefunguje.

**Comment by milant007** [comment]
takto to uplne staci, vyskousel jsem a super! :) ale tyto veci klidne res po sleze, ted hlavne formular auta a faktury.
