### ISSUE TITLE
posouvani maleho gridu

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#31]
Ahoj,
pro male gridy < 50 radku nepouzivam VirtualList ale jednoduse  primo <div> elementy.
Akorat se mi tam neposouva header (horizontalne),  coz si delal pro VirtualList  - udelej to prosim o pro tento pripad.

Je to v GridComp.js

Myslim, ze kdyz pridavas filtr do gridu tak uz grid zustane jaky byl (Virtual / NeVirtual) , takze to jednoduse nasimulujes treba na detailu customera, na subgridech.

Kdyz tak se ozvi,
dik, h.

**Comment by martinnemec3** [comment]
Pridal jsem scrollEvent pro rowContainer, ve kterym se header posune do stejny pozice (stejne jako je event na virtuallistu). Ted by to melo bejt ok, dam PR.
M.

**Comment by jzelenka** [comment]
dik
