### ISSUE TITLE
poladit grid column width

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#33]
Kdyz ma pole kratky header a ne uplne kratke hodnoty, tak se ty hodnoty zkrati.
Asi zvlast v pripade ze hodnoty maji konstatni delku, tj, neni tam nejaka ktera by byla o hodne delsi a tim vynutila zvetseni.

Videt je to dobre na polich Ico, Dic na Party / Customers.

Jeste je zajimave ze Ico je o dost vic zkracene nez Dic.

Chtelo by to vyresit bez toho aby se prodlouzilo vsechno (i tam kde to neni potreba), Tj. idealne kdyby se na gridu Customers rozsirili jen pole Ico, Dic a mozna Sales R. Name.

Ovsem nevim jestli lze takto algoritmus poladit....

Zhruba pred mesicem jsem menil font Roboto na Roboto Condensed, mozna to predtim nedelalo... (ale tam kde umele vkladas div abys zjistil sirku, jsem font snad zmenil taky).

**Comment by martinnemec3** [comment]
Myslim si, ze problem by mohlo zpusobovat to, ze v gridService.js se pri vypoctu pouziva font-size: 12px, kdezto v gridech mas 13px. Maji vsechny tabulky font-size 13px? Pokud ano, staci to prepsat; pokud ne, budeme muset pocitat nejak dynamicky.

Kazdopadne ja to tady neotestuju, protoze Chrome, Chromium i Firefox mi to zobrazujou v pohode i bez zmeny.
M.

**Comment by jzelenka** [comment]
v gridech je snad vsude 13px

**Comment by martinnemec3** [comment]
tak to asi ani nebudu commitovat, gridService, radek 167: font-size na 13px. Snad to pomuze.

M.

**Comment by jzelenka** [comment]
super, funguje :)

**Comment by martinnemec3** [comment]
Pokud by se do budoucna delaly gridy s jinou velikosti pisma, bude potreba na to myslet.

M.
