### ISSUE TITLE
umisteni linek (podtrzitek) u TextField s multipleLine true

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#34]
TextField s multipleLine true se renderuje jako textarea a nefunguje u nej spravne umisteni linek (podtrzitek).
Je to dusledek zmenseni TextField.
Nezapomenout na errorLine.

Pouzito na detailu produktu.

**Comment by martinnemec3** [comment]
Koukam ze to tam je takovy dost divoky... asi teda udelam zase obalovou komponentu...
M.

**Comment by martinnemec3** [comment]
Jedna technicka - vysku te komponenty nastavujes na 54px a zaroven po ni chces, aby byla triradkova... to asi nepujde dohromady (pri teto velikosti pisma). Takze potrebuju ted vedet, jestli ji chces mit triradkovou nebo 54pixelovou

**Comment by jzelenka** [comment]
54px vzniklo pri tom zmensovani textfieldu. Pro textArea to muzu nenastavovat nebo nastavovat na nejaky nasobek poctu radku.

Technicky to tam propadne z createform HOC komponenty, ale jde asi overridovat uz tam (pak by rows byl parametr na field definitions) nebo primo u jsx policka.

**Comment by martinnemec3** [comment]
Tak jestli chapu dobre, prioritou jsou tri radky

**Comment by martinnemec3** [comment]
Zda se, ze postaci opravit ten jeden bootstrap styl (dal jsem to do zauzoo-bootstrap.less) a smazat tech 54px ze style (to jsem udelal zatim v productForm.js v render() - kdyztak to presun). Mozna by nebylo spatny rows zmensit na 2, pri 3 mi to prijde moc velky, ale to udelej jak se to bude zdat tobe. Udelam PR.

**Comment by jzelenka** [comment]
Prazdne pole uz vypada dobre, ale kdyz se do nej zacne psat, tak je to zas blbe.

![image](https://cloud.githubusercontent.com/assets/1957955/12529497/da211c68-c1b8-11e5-99ad-337180cdcd41.png)

**Comment by martinnemec3** [comment]
Odstranil jsem teda jeste styly "floatingLabelStyle" a "inputStyle" - ted se to zobrazuje korektne, nicmene zabira to dost mista... Mrkni na to (dam PR)

**Comment by jzelenka** [comment]
dobry, dik, zaviram
