### ISSUE TITLE
zavirani StyledSelect pri kliku na scrollbar

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#35]
Po upgrade react-select na verzi 1.0.0-beta8 dojde po kliku na scrollbar rozbaleneho selectu (kdyz chci zarolovat - potahnout scrollbar) k zavreni selectu.

Ale pouze v detailu, treba na detailu party. Ale ne treba v definici gridu.
Tedy pouze v tech formech, ktere vznikaji na klik (vsechny standardni detaily v zauzoo, ale ne treba v definici gridu).

Takze je to trosku tricky...
Downgrade bych nerad, pouzivam tam i jine veci..

**Comment by martinnemec3** [comment]
Tady tomu moc nerozumim, kazdopadne to zpusobuje vlastnost tabindex, ktera se nastavuje hlavnimu DIVu v komponente ActiveItem (finalProps.tabIndex v souboru activeItem.js). Pokud ji ostranim, chova se StyledSelect spravne tak jak ma - pri kliku na scrollbar se nezavira.

**Comment by martinnemec3** [comment]
BTW: pokud je activeItem ve stavu "open", je nad nim tabindex asi zbytecnej nebo ne?

**Comment by jzelenka** [comment]
Super za zjisteni ze to dela tabIndex !.
Daval jsem ho tam, kdyz se zjistoval jestli tohle reseni formu pujde ovladat bez mysi....
Na to tedka prdime, stejne to nebylo dotazeny...

Ten tabIndex je stejne nejakej divnej, kdyz ho dam jen na activeItem ve stavu "close", tak stejne nejak preleze i na ten div "open", ale s hodnotou -1 !
Takze jsem ho musel uplne vyhodit.

Ale to je ted fuk, jednak na mys zatim kaslem, jednak to muze react-select opravit, konec koncu pred upgradem to nedelal ani s tabIndexem.

Zaviram.
