### ISSUE TITLE
upgrade material-ui

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#39]
Material UI mame nyni na 0.14.0,
chtel bych upgradovat, ale v 0.14.3 udelali (viz changelog) :

> ### Breaking Changes
>
>Note that these are not essentially breaking changes. Unless you have used these implementation details in your code.
>
>    [Internal] Remove controllable.js mixin (#2889)
>     [Internal] Remove mergeAndPrefix() (#2886)
>     [Internal] Remove utils/extend.js (#2933)
>     [Internal] Remove utils/immutability-helper.js (#2907)

ktere se pouzivaji v tech hackovanych komponentach: `StyledSelect, StyledDatePicker, NumberInput`
... ktere jsi delal ty :)

**Comment by jzelenka** [comment]
k nahrade mergeStyles se muze hodit Object.assign() - ja to pouzivam na klonovani:
 
      let clonedObject = Object.assign({}, objectToCopy);

a k mergovani:

      let mergedObject = Object.assign(targetObject, higherPriorityObject, highestPriorityObject, ...);


Dale muzes pouzivat vse z ES6, ES7  (mame babel stage 0)
a taky i veci, ktere nejdou transpilovat (ale musi se polyfilovat), mame babel-polyfill, coz je v podstate core.js (https://github.com/zloirock/core-js)

takze treba array#includes() nebo Object.values() funguje.

Dale mame lodash v posledni verzi.

**Comment by martinnemec3** [comment]
Upgradoval jsem to a podle toho co jsem proklikal to vypada, ze to funguje. Dam PR.
