### ISSUE TITLE
Nejde zmena datumu platnosti v product vehicle

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#40]
Vyberu auto, pak balicek dam edit, zmenim datum a kdyz chci potvrdit, tak to vyhnije na chybe: 
Server error 500
NullPointerException:

**Comment by jzelenka** [comment]
nj, to je regrese ze sum na gridu :(
dokud nebudou aut. testy tak se to bude stavat....

fixed, deployed.

**Comment by milant007** [comment]
to neva, jsou v poho. uvidime, jak dlouho jim nadseni vydrzi. :-)

jeste k tomu mam jednu vec, nastavil jsem platnost balicku od 1.3.2016 
...a ted jsem s nima resil po telefonu ze by chteli videt radeji cenu 0 a teprve az nastane 1.3.by se dotahla platna cena. 
Nebo idealne videt obe, to znamena za kolik by se to ted fakturovalo a za kolik se to fakturuje. Ale kdyby to byl vopruz nebo dalsi velky zpomaleni, tak pridat podminku na platnost balicku a pokud neni platny tak dat cenu za 0.

**Comment by jzelenka** [comment]
je to tam. Nechal jsem to:
chybi cena v cenotvorbe: prazdno
neplatny balicek: 0

Jinak pri editaci cena vzdy zmizi a objevi se az po ulozeni.
