### ISSUE TITLE
Export gridu do XLS

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#41]
Bylo by dobry mit funkci na export gridu do xls...

+ jen pro Volvo pridat sloupecek valid_price(suma za vehicle valid_price) do gridu Customers

pristala nam prosba exportu zakazniku co se fakturuji a toto by to vyresilo. pripadne kdyby to nebylo slozity napsat termin kdy by to bylo?

**Comment by jzelenka** [comment]
valid_price jsem pridal (do gridu si ho pridej sam - trosku do brzi, tak si rozhodni jestli jim udelas novy grid nebo to pridas do Customers)

export gridu bude asi dneska, je to mensi vec tak to predradim dodelani faktur.

**Comment by milant007** [comment]
super, urcite udelam vlastni grid

**Comment by jzelenka** [comment]
excel starej nebo novej (xslx) ?

**Comment by milant007** [comment]
Nemam na to nazor, starej je pry lepsi pro zpracovani i v ostatnich open programech ale ma omezeny pocet radku, myslim 32000. Fakt nevim, je to asi jedno

**Comment by jzelenka** [comment]
je to tam.
