### ISSUE TITLE
Nesumuje se Valid_Price v detailu vozidla

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#47]
Valid_price v detailu vozidla se nesumuje. Asi jak jsi tam pridaval měnu nebo možnost to přímo tam vyplnit.
Ja bych tam pripadne zobrazil dva sloupce pokud by to pomohlo vyresit, jeden PriceVehicle, coz by bylo pouze v pripade, ze si zadaji cenu primo na tom aute, a Valid_Price zachoval tak jak bylo, tedy aby byla videt cena, i kdyz mam auto nenaceneny, nebo?

**Comment by jzelenka** [comment]
Opraveno, mena sumy je natvrdo EUR (tj. pokud by mena ceny polozky (balicku) nebyla EUR, prepocte se).

Casem, kdyz bychom chteli podle neceho (customer auta, tenant....) nastavit menu sumy, tak to musime rozmyslet.

Sloupecek PriceVehicle k tomu nepotrebuju, pokud bys ho chtel, tak to otevri. Ale na cenu na urovni PRODUCTVEHICLE se muzou podivat rozkliknutim na detail.

Nasazeno.
