### ISSUE TITLE
Chyba pri zakladani vozidla z party

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#48]
Zároveň mám problém keď sa nahadzuje vozidlo, nižšie prinscreeny. Dám si zákazníka, vyberiem moznost pridat nove vozidlo, vyplnim SPZ, VIN, Brand, Aktivacny datum, Dam Uložiť a toto je výsledok:
Vysledek je, ze se toci kolecko a nic se nedeje.

**Comment by jzelenka** [comment]
opraveno, nasazeno.
