### ISSUE TITLE
Nejde otevrit detail party customer

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#49]
chyba:

Client Error
TypeError: n.hasRole is not a function at http://zauzoo.com/module-85c2845c.js:42:3243 From previous event: at Function.p.value [as fetchData] (http://zauzoo.com/module-85c2845c.js:42:3136) at http://zauzoo.com/module-85c2845c.js:40:11168 at Array.reduce (native) at Function.<anonymous> (http://zauzoo.com/module-85c2845c.js:40:11120) at Function.B (http://zauzoo.com/common-85c2845c.js:53:18526) at http://zauzoo.com/common-85c2845c.js:53:18286 at e.u.value (http://zauzoo.com/module-85c2845c.js:1:7745) at http://zauzoo.com/common-85c2845c.js:75:13567 at http://zauzoo.com/common-85c2845c.js:75:13627 at Function.o.to (http://zauzoo.com/common-85c2845c.js:75:13635) at http://zauzoo.com/common-85c2845c.js:53:18261 at http://zauzoo.com/common-85c2845c.js:75:13434 at e.u.value (http://zauzoo.com/module-85c2845c.js:1:8416) at http://zauzoo.com/common-85c2845c.js:75:13373 at Function.o.from (http://zauzoo.com/common-85c2845c.js:75:13442) at Function.c.createClass.statics.dispatch (http://zauzoo.com/common-85c2845c.js:53:18193) at Object.c.createClass.statics.handleLocationChange (http://zauzoo.com/common-85c2845c.js:53:17610) at http://zauzoo.com/common-85c2845c.js:16:28920 at Array.forEach (native)

**Comment by jzelenka** [comment]
opraveno (az dobehne build).
