### ISSUE TITLE
Nejde ulozit auto po odebrani balicku

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#50]
Po odebrani balicku z auta se pri naslednem ulozeni objevi tato chyba:

Server error 500
JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token at [Source: java.io.PushbackInputStream@ef640fc; line: 1, column: 462] (through reference chain: com.zauzoo.core.grid.util.dto.DataObjectDto["gridData"]->java.util.LinkedHashMap["vehicleProductList"]->com.zauzoo.core.grid.util.dto.EditedGridDto["deletedRowIds"])

**Comment by jzelenka** [comment]
jo jo, uz na tom delam - uzivatel buzalka :)

**Comment by jzelenka** [comment]
opraveno (build running)
