### ISSUE TITLE
Dotaz VOLVO SK

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#52]
Přeposílám dotaz z VOLVO SK, já totiž ani nevím jak to bylo před tím, pak asi musime probrat:

Chcel by som sa informovať, či by bolo možné zmeniť nastavenie pri zadávaní kontaktov, aby sa nerolovalo ale celé posunulo keď sa zadáva viac kontaktov naraz. Niekedy to tak fungovalo, že tam nebolo rolovacie okno. Bolo by možné to nastaviť tak ako to bolo, alebo nie? Ďakujem za info
![volvo_sk](https://cloud.githubusercontent.com/assets/13977376/14909804/b37e54ec-0de7-11e6-9983-a7ca22cf8069.jpg)

**Comment by jzelenka** [comment]
No jo, ja vim.
ja jsem dal maxHeight na sekci kontaktu, mysleno to bylo aby, v pripade mnoha kontaktu, to neodsunulo subgridy moc dolu, respektive aby je to neudelalo moc male, protoze nemame globalni posuvnik.

Jenze on ten maxHeight otravuju kdyz to otevru k editaci. Ja to zatim vyresim tak, ze ho zrusim, v realu  asi party moc kontaktu nemaji.

Nasledne:
- zkusim predelat design tak, aby to nebylo "bez globalniho posuvniku, vse se vejde na obrazovku, ala desktop"  ale aby to byla rolovaci webova stranka. Ale nevim jestli to pujde. Zejmena na detailech s taby a levym sloupcem....

**Comment by jzelenka** [comment]
Je to tam.

Udelal jsem jen push do repository (githubu), do 5 min se automaticky spusti build testu - tam se na to muzes podivat, nasledne si sam udelas deploy do produkce. Jen FE - deploy FE je uplne bez vypadku (po refreshi se jim to objevi).

Takhle to budu delat vzdycky, pokud to udelam jinak (budu se treba chtit podivat na produkci, nebo to bude nejaky citlivy update, ktery si budu chtit udelat sam), tak to napisu.

Jinak mam tam ted management SQL zmen v aplikaci (Flyway) , coz znamena ze se zmenove skripty aplikuji automaticky (pouziva to trackovaci tabulku, kam si pise co se uz aplikovalo), samotne zmeny jsou soubory ve zdrojacich BE.

Pak to funguje tak, ze kdyz se nejake zmeny udelaji naprimo, tak se do toho flyway vubec nedaji, protoze jinak by to spadlo (column already exists apod.) A musi se udelat ve vsech prostredich nebo obnovit produkci do testu, devu.
