### ISSUE TITLE
V menu Export dodelat ikonu pro stazeni do souboru

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#53]
Dodělat ikonku na uložení stahovaného exportu do souboru přímo do menu. Text otevře, ikonka stáhne.

**Comment by jzelenka** [comment]
Hotovo, pushnuto.
@krivohlavek Jindro na sablone InvoicesHuScalaXls mas spatne format - mas XML, ma byt Excel.

Na vlastni obsah souboru to sice vliv nema, ale spatne se nabizi koncovka souboru pri download a nastavuje content-type pri open-in-browser.

**Comment by krivohlavek** [comment]
@jzelenka To je úmyslně.

Co jsem hledal, tak xslt -> xlsx vytvoří pouze soubor s daty (xlsx je zip obsahující hromadu souborů). Když se to pojmenuje jako xml a excel je nastaven na otevírání xml, případně se to v něm otevře tak to chodí ok. Když dám příponu xlsx tak to řve o poškozeném souboru (možná to jde potvrdit a otevřít, ale kdyby byl náhodou soubor poškozen tak to uživatel nepozná). Aby to bylo korektní xlsx tak to bylo dost práce navíc - z Volva to zkoušeli a takhle jim to chodí.
