### ISSUE TITLE
Drop down list box

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#54]
Kdyz zadavam pole v Party napr. "Default language", tak nereaguje na stisk klavesy a musim rozkliknout, kdyz to samy udelam napr. "Default Currency" a stisknu e tak se mi predfiltrujou pouze meny zacinajici na E. 
To je poznamka od Vítka, mně to bylo šumák, ale on to hned řešil.

**Comment by jzelenka** [comment]
To je udelane schvalne, do dropdownu, ktere maji mene nez 8 hodnot nelze psat (filtrovat).
Udelal jsem to tak, protoze me prislo osklive, kdyz se da psat do dropdownu, ktery ma malo hodnot. U dropdownu s hodne hodnotami uz ta filtracni funkce za to stoji.

Jinak rozkliknout se to da i sipkou dolu.

Muzu to samozrejme zmenit.

**Comment by milant007** [comment]
To dava smysl, jen bych to asi  udelal jen na mnozstvi, kdy se nemusi v tom dropdownu skrolovat?

**Comment by jzelenka** [comment]
takze 4?

**Comment by milant007** [comment]
asi jo

**Comment by jzelenka** [comment]
fixed, pushed.
