### ISSUE TITLE
Hlášky v CZ

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#55]
Vítek teď školí Rumuny na TESTu a např. hláška o úspěšném uložení Party je v Češtině. Prosím hodit vše kde se vyskytuje čeština do EN. 
Nebo pokud je ta hláška lokalizovaná, tak kde nastavím aby s rumuny ZZ komunikovalo v EN jazyce?

**Comment by jzelenka** [comment]
neni to lokalizovane.
lokalizace je na dyl, v prvnim kole bych to prelozil do anglictiny. Nemohl by to projit nekdo u vas?

**Comment by milant007** [comment]
ja to projdu, zatim je to v cestine na party pri ukladani.

**Comment by milant007** [comment]
tak je to obecne jakekoliv "SAVE" ve vsech modulech

**Comment by jzelenka** [comment]
"ja to projdu" znamena i "ja to opravim" ?

**Comment by milant007** [comment]
kdyz mi reknes jak, tak to i opravim :-)

**Comment by jzelenka** [comment]
jednodusi asi bude kdyz ti ro rekne martin?

**Comment by milant007** [comment]
super, mame prelozeno :-)
