### ISSUE TITLE
Comment ve Fakture viditelny

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#57]
Kdyz vlezu na detail FA tak pred vystavenim by bylo dobry videt comment nejen pokud rozkliknu tu sipku dolu ale vzdy. Zase jde hlavne kdyz se kopirujou zakazky. Ted jsem zkopiroval Heiru posledni FA za upravy. Zas je to jednodussi nez zakladat novou a jen pripadne upravim pocet hodin/dnu. Ale v commentu mam napsano za jaky mesic a jak jsem to nevidel, tak mi tam vlitl "duben".

**Comment by jzelenka** [comment]
tohle uz je hotove
