### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#58]
Pozadavek z RO, nastavime podle tax domicile z party co je na tenantovi nebo individualne podle tenantu/tenant groups?
Hello team,
Please change the date format for Romania from mm/dd/yyyy to dd/mm/yyyy.
Thank you,
Alexandru

**Comment by jzelenka** [comment]
date format je nastaven dle zvoleneho jazyka v aplikaci.

Jazyk aplikace se nejprve nějak určí podle defaultního jazyka OS (každý OS a prohlížeč to má jinak). Ale při zvolení (přepnutí) jazyka v aplikaci (nahore vpravo) se tato informace zapamatuje (pro daný prohlížeč a počítač) a při příštím spuštění se použije.

Takže rumun si nastavi ro a když přijde podruhy k pocitaci tak tam bude ro.

Duvod proc to neni dle uzivatele (nebo tenanta) je ten ze už login stranka by mela byt lokalizovana a v tu dobu jeste neni uzivatel znam. Taky zmena jazyka je resena reloadem stranky v browseru, tedy restartem cele SPA a to by nebylo dobre delat pri loginu.

Rumunsko ma dle https://en.wikipedia.org/wiki/Date_format_by_country format jako my  - dd.MM.yyyy

Dale jsem sjednotil pro EN format mm/dd/yyyyy  (on už byl v datepickeru, ale read-only pole (grid, zavreny formular) pouzival dd/mm/yyyy.

Doplnil jsem formaty taky pro sk (jako my) a hu (yyyy.MM.dd.)

Doplnil jsem to do https://github.com/zauzoo/app/wiki/Lokalizace

**Comment by jzelenka** [comment]
je otazka jestli nedat pro EN dd/mm/yyyy , protoze krome US to pouziva vetsina sveta...

**Comment by milant007** [comment]
jo, zmen to.
