### ISSUE TITLE
Invoice details pres tenanta

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#59]
Na Volvu jsem narazil na to ze Invoice details jsou videt pro vsechny VOLVA.
- ono to neni chyba ale vetsinou nas zajimaji pouze Details z vlastni fakturace. Takze bych to vyresil upravou gridu Invoice Details kde bych nejak zapracoval podminku na aktualne prihlaseneho tenanta.
- A pak bych udelal vlastni grid kde by to slo pres celou tenant group jak je to do ted.

**Comment by jzelenka** [comment]
kde ty Invoice details presne jsou ?  party, auta, produkty?
Co vlastni Invoice ?

Je mozne ze to dela pouze na produktu a dela to jak invoiceItem, tak Invoice ?

protoze produkty jsou sdilene v ramci tenantGroup Volvo?

**Comment by milant007** [comment]
tyka se to produktu, protoze jsou v ramci tenant group a pouze na InvoiceDetails

**Comment by milant007** [comment]
Ted jsem si vsiml ze u polozek FA tedy tabulka din_invoice_item si uklada tenant_id = 0 u vsech FA. Tim se vysvetluje proc jsou ty polozky FA videt pres tenanty. Premyslim ze kdyz tam dame toho tenanta ke kteremu to patri, tak to zas nebude pres tenanty videt nikdy. Tak jen chci vedet zda to mas schvalne?

**Comment by jzelenka** [comment]
nemam :) 
to je chyba, ma tam byt tenant.

Updatnu data (podle invoice) a opravim v kodu.

No ted to nebude videt nikdy, az v tom olapu...

**Comment by jzelenka** [comment]
opraveno. nedava se 0.
