### ISSUE TITLE
vyberove checkboxy a podbarveni

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#6]
Prosim o:
- pri zapnuti "Show selection", kdy se objevi checkboxy, je treba opravit sirky, aby se neobjevoval horizontalni scrollbar (pokud neni nutny).

- implementovat "multi selection"  stejne jako to ma table v material-ui  (select all checkbox, shift+click obarvi celou oblast, ctrl+click prepina jednotlive radky se zachovanim selekce - stejne se chova excel pri vyberu bunek)

 viz http://material-ui.com/#/components/table
 je treba si zapnout `Selectable`, `Multi-Selectable`, `Enable Select All` ...
doporucuji si udelat checkout a podivat se do zdrojaku, maji to celkem dobre napsane, clovek se pouci...

- implementovat hover podbarveni, opet viz table v material-ui a `show row hover`
  ale pouze kdyz gridConfig.showRowHower = true

**Comment by martinnemec3** [comment]
Kombinace CTRL+Click se mi zda u Multi-Selectable zbytecna (i bez drzeni CTRL se oznacovanim dalsich radku tyto pridavaji do vyberu). Jsou tedy dve moznosti, jak udelat aby se to chovalo:
* na obycejny klik bez drzeni klavesy oznacovat jen jeden radek a zrusit oznaceni pripadnych dalsich (tak jak se chova tabel v material ui bez Multi-Selectable) a pomoci CTRL+Click zajistit funkci Multi-Selectable
* na CTRL se vykaslat a nechat tabulku stejne jako v pripade multi-selectable (klik na radek pridava tento radek do vyberu, po kliknuti na nej znovu se odebere z vyberu)

**Comment by jzelenka** [comment]
Koukal jsem jak funguje gmail a je to stejne jako material-ui s multi-selectable.
Takze jo,  plati varianta 2 ( a nezapomen na SHIFT + click, ten plati).

Stejne budeme ty checkboxy pouzivat na multi vybery (operace nad jednim radkem se budou spoustet jinak) takze nevadi ze to zustane oznacene, kdyz tak si to zresetuji zakliknutim a odkliknutim Select All.

**Comment by martinnemec3** [comment]
Dalsi vec je, jak by se melo oznaceni chovat v pripade zadani vyhledavaciho vyrazu. Melo by se v tu chvili oznaceni zrusit, ponechat u tech radku, ktere se zobrazuji ve vysledku, nebo ponechat v pozadi i pro ty radky, ktere zobrazeny nejsou?

**Comment by jzelenka** [comment]
Asi je jednodussi to zresetovat.
Jak to budes delat? Kam ulozis informaci o vybranych radcich?
do state nebo do props?

Pokud do props, taky asi primo do dat - treba pridat do radku `grid.data.rows[x].selected`
Pak budes asi muset zavolat action `GridActions.updateGrid`  dle zasad fluxu (pouzivame alt)
Protoze primo menit props se nema/nesmi/nefunguje to

Taky se musis rozhodnout jestli checboxy budou controlled nebo uncontrolled, viz. https://facebook.github.io/react/docs/forms.html

Jo <form> element kolem gridu taky mozna neni, ale mozna neni potreba (kdyz nedelame submit treba na enter) nevim.....

**Comment by martinnemec3** [comment]
* No myslim ze bych ukladal rowId do mapy do state, pak by byl seznam vybranych radku vzdy hned k dispozici.
*V tim gridu si myslim ze museji bejt controlled, protoze je to vzdy renderuje znova kdyz clovek scrolluje.

**Comment by jzelenka** [comment]
tak to zkus, pak je musis na search resetovat

**Comment by martinnemec3** [comment]
Nejakej tip, kdyz se mi nechce prekreslit checkbox? Mam problem s tim checkboxem pro oznaceni/odznaceni vsech radku (je controlled). Kdyz na nej kliknu, tak se vse provede, ale zustane nezaskrtlej (ackoliv hodnota je nastavena spravne). A staci kdyz treba maximalizuju nebo resizuju okno a uz se vykresli spravne. Zkousel jsem nad nim forceUpdate(), ale nepomaha. Jen jestli s tim nemas zkusenost, uz jsem nad tim stravil dost casu.

**Comment by jzelenka** [comment]
A nastavujes v jeho onChange handleru state ? respektive polozku statu, ktere ho trackuje (kterou mas  nastavenou v jeho value) ?

**Comment by martinnemec3** [comment]
Tak konecne to funguje - problem byl teda v tom, ze jsem v jeho "checked" mel porovnani dvou hodnot. On tam zrejme ocekava primo polozku z props nebo state.

**Comment by martinnemec3** [comment]
Dik moc

**Comment by martinnemec3** [comment]
Co se tyce toho podbarvovani, do gridConfig tedy pridam polozku showRowHower a na zaklade ni se pak bude pod mysi podbarvovat?

**Comment by jzelenka** [comment]
Ano
