### ISSUE TITLE
Zobrazit pole actvive v detailu Vehicle

### ISSUE THREAD

**Issue by milant007** [zauzoo/fe#61]
potřebuji zobrazit pole active(true/false) v detailu  vehicle. Importem se tam dostaly i neexistujicí auta a ještě se na ně navíc fakturovalo. :-( Takže nejdou smazat, ale nikam nepatřej, potřebuji je úplně deaktivovat.

**Comment by jzelenka** [comment]
Jo, jen jsem dnes v estonsku, zitra.

**Comment by milant007** [comment]
jeste prosim v detaile vehicle povolit customera null, pokud customer auto proda, tak musi zustat auto v DB kvuli historii ale nema majitele... 
nevim zda uz je na urovni tenanta unique key na VINko?

**Comment by jzelenka** [comment]
unique key na VINko neni, jsou tam duplicity, ale vsechny jsou v CR.
Kdyz to vycistis, tak si myslim ze unique key by mel byt globalni, nikoliv na urovni tenanta.
Je tam aplikacni kontrola na globalni VINKO - nedovoli ti zadat duplicitni pres GUI. Asi jsi to do CR dostal importem.

select vin, tenant_id, count(*) from dpr_vehicle group by vin, tenant_id having count(*) > 1
select vin, count(*) from dpr_vehicle group by vin having count(*) > 1

**Comment by milant007** [comment]
ČR je promazany. ALE je tam jedno VINko, který je v tenantu 2 a 7: **YV2AG20A3BB576277**
Jedná se o to, že jezdilo v nějaký SK firmě a je na něj fakturační historie. Ta firma to auto prodala do RO a od 1.10. se bude fakturovat v RO. 
Za mě ideálně jedno VIN v rámci celé DB, ale jak vyřešit, že chci ve vybraných tenantech vidět pouze auta co jezděj v tu chvíli právě v té dané zemi?

**Comment by jzelenka** [comment]
zmenit u nej tenanta?

**Comment by milant007** [comment]
ale co to udela u tech starych Faktur v původním tenantovi kdyby se v tom nahodou někdo štoural? bude tam vidět SPZ, VIN...? Jak ten uživatel co to v RO zakladá pozná, že to již v DB existuje. On akorát dostane pokyn založ tohle auto u tohoto zakazníka s těmito balíčky... a nemá tušení, že již bylo zakložený v SK.

**Comment by jzelenka** [comment]
tak bude unique key a ta kontrola teda jen v ramci tenanta.

**Comment by milant007** [comment]
ok, pro ted to je asi nejjednodussi, ale porad mi prijde nejcistsi reseni jedno VIN v ramci cely DB. Ale to by se konec koncu dalo rict i o IČ v rámci země a IČ...

**Comment by jzelenka** [comment]
kontrolu na VIN jsem zmenil ze je jen v ramci tenanta. Takze pres GUI duplicitni nikdo nezada. Unikatni index delat nebudu.

**Comment by jzelenka** [comment]
active / false je hotove:
- je to ikonka u hlavniho nazvu na zavrenem detailu, prepina se kliknutim, uklada se hned bez info zpravy, do historie se uklada.
- je to na Vehicle, Party, Product
- na gridu je zavreny (neaktivni) entita preskrtnuta
- muzes jim udelat treba defaultni grid active only a pak treba druhy pro vsechny nebo jak chces
