### ISSUE TITLE
stylovani react-select

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/fe#8]
Pro vybirani hodnot budeme pouzivat komponentu react-select.
Je uz pouzita v Manage Grid (Grid / vyber gridu / manage - Vyber sestavu - dole v "Aplikuj výběrové filtry" )

Je potreba ji trochu ostylovat do material design (transparent background, jen podtrzitko)

**Comment by martinnemec3** [comment]
Tady bych asi byl pro udelat novou komponentu v src/core/components a v ni vyuzit react-select a prestylovat ho - abychom ho pak takhle nastylovanej mohli pouzivat vsude. (prepisovat to primo v node_modules se mi nezda jako dobrej napad)

**Comment by jzelenka** [comment]
prepisovat primo v node_modules urcite ne. Ale mozna to pujde udelat ciste pres styly (lessove ne embedded js v style, tj. className ne style).

Jinak ja chtel k tomu jeste neco napsat, proto jsem ti to neprirazoval.....

Nemam zatim uplne jasno v tom, jestli budou:
 - jedna zastresujii komponenta pro vsechny typy (text, number, date, datime, select)
 - ruzne komponenty pro search / editaci... 

Ted teprve dodelavam editaci gridu, pak zacnu delat detail Party a uvidim jak se to vyvrbi.

Samozrejme editaci v node_modules ne ! - node_modules neni ani v gitu.
Fork je taky az posledni moznost - prijdeme o upgradovaltenost

Nejdriv bych zacal s classama - takze pres property className
  - pri tom muzes identifikovat pripadne nezadouci globalni styly, ktere tam prinesl bootstrap

pak je tam valueRenderer a optionRenderer.

**Comment by martinnemec3** [comment]
Tady asi neni nic moc co stylovat, kdyz se tomu da pruhledny pozadi i bordery. Jediny co by chtelo pridat - to podtrzeni ma material-ui delany specialnim DIVem, kterej by tam bylo treba pridat (pokud se to udela borderem, je to moc dole)

**Comment by jzelenka** [comment]
slo by to podtrzeni vyresit bez forknuti knihovny? treba pomoci valueRenderer property....

**Comment by martinnemec3** [comment]
Pres ten to tam asi pujde nejak dostat a dostylovat. Ten ale pak bude treba dodat ke kazdymu tomuhle selectu, takze by bylo dobry asi ho umistit nekam do components?
M.

**Comment by jzelenka** [comment]
jo to jo, udelej to tak...

**Comment by jzelenka** [comment]
Dale je potreba pridat error styl - idealne jako v 
http://material-ui.com/#/components/text-fields

**Comment by jzelenka** [comment]
Tedy kdyz je zadany errorText
`if (errorText)` 
tak zobrazit linku cervene a pod ni ten text

vubec asi, v te samostatne komponente, by mely byt implementovane metody a eventy jako v TextField.

**Comment by martinnemec3** [comment]
Jeste se vyskytnul jeden problem a to je, ze valueRenderer se vyrendruje jen pokud je zvolena nejaka value. Tzn. ze pokud neni zvoleno nic, nebo uzivatel treba pise search text, tak se vystup valueRendereru nezobrazi a tim padem ani barevne podtrzeni. (hodilo by se neco jako emptyValueRenderer)

**Comment by jzelenka** [comment]
Co navrhujes?

**Comment by martinnemec3** [comment]
Jeste zkusim prolezt kod toho react-selectu, jestli by se to pres neco nedalo ohnout...
Jinak to bude bud:
* nechat to zatim takhle a dat treba pozadavek na emptyValueRenderer na GitHub
* forknout react-select

**Comment by jzelenka** [comment]
jestli to nepujde, tak dat pozadavek a forknout :) , nevime kdy a jestli ho splni....
forknout muzes do zauzoo/react-select, jestli mas prava. Potom asi release do npm... nebo to v zauzoo/fe/package.json brat z githubu, to snad jde, brat primo master nebo nejakou branch.

Z toho forku jim muzes rovnou udelat pullrequest...
h.

**Comment by martinnemec3** [comment]
Zatim by se dalo vymyslet nejaky temporary-solution pomoci treba background-image

**Comment by jzelenka** [comment]
ok, cokoliv aby to trochu vypadalo... fork je samozrejme neprijemnej, to je az posledni moznost.

**Comment by martinnemec3** [comment]
Konecne se mi povedlo to dostat do nejakeho stavu, ze to trochu vypada... co se tyce toho error textu - myslis tim pridat propType errorText?

**Comment by jzelenka** [comment]
Ano a i ty ostatni.

       ... by mely byt implementovane metody a eventy jako v TextField.

**Comment by jzelenka** [comment]
teda ty ktere davaji smysl

**Comment by martinnemec3** [comment]
Konecne to nejak asi je, uz jsem myslel, ze z toho vyrostu - jeste peklo, ktery mi dalo zabrat byl "multi" select :( Snad uz to bude ok. Implementovany property jsou zatim name, valueRenderer, value, options, onBlur, onChange, onFocus, clearable, multi, delimiter a placeholder. Pokud bude potreba neco z react-select, staci to tam dopsat, pokud neco z material-ui fieldu, tak se to dopise.
M.

**Comment by jzelenka** [comment]
no jo, ja vim :)
diky, cekam na PR

**Comment by martinnemec3** [comment]
U "multi" selectu nefunguje modre podtrzeni (podtrzitko zustava sede). Je to proto, ze se value renderer spousti pro kazdou z tech zadanejch hodnot zvlast, takze by to vedlo na hodne ohybani a hodne.

**Comment by jzelenka** [comment]
ok, zatim to nechame.... nejak to pak v klidu budeme resit pozdeji.

**Comment by jzelenka** [comment]
uz to edituju rovnou v masteru.... 
zaviram a davam nice to have na modrou linku na multiselect aby se nezapomelo.

**Comment by jzelenka** [comment]
ma ted natvrdo fontSize 16px a minheight 48px

Nechci aby to bylo natvrdo, chci mit moznost dat mu mensi font a chci aby se pak vyska celeho elementu patricne zmensila.

Tedy aby tam fontSize a minHeight vubec nebylo.

Kdyz jsem to zkusil vyhodit (a jeste manipuloval lineHeight) tak se rozjela seda a modra linka
Tak to hodim na tebe :)

Pokud mas problem s alignovanim te linky - zkousels css flexbox ? (a ridit umisteni pres align-items / align-self) ?
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by martinnemec3** [comment]
Ja se dost z tech stylu snazil udelat podle TextFieldu, kde vyska tech 48px byla, ale zda se ze tam se dost tech stylu generuje jako inline primo tomu elementu v zavislosti na tom, jaky styly mu predas v definici.

**Comment by jzelenka** [comment]
no to asi jo ... ja nemam nazor na ty js inline styly versus css.

Cetl jsem nejaka zduvodneni proc jsou js inline styly lepsi, ale prijde me ze jsou lepsi mozna tak pro sveho autora.... kdezdo css lze menit vzdy a kazdy...

udelej to co ti prijde jednodussi....

**Comment by martinnemec3** [comment]
Dostal jsem to do situace, kde se to chova stejne jako TextField z material-ui, ma to stejny styly (defaultni vysku 48px, atd...) Problem ale dela multi - tam nemam moc predstavu, jak to udelat, aby to bylo konzistentni s material-ui komponentama. Treba kdyz das u TextFieldu "multiLine=true" tak se v kodu javascriptove vypocita jeho vyska v pixelech podle poctu radku, ktery si zvolis. To tady asi nepujde. Tva predstava je mit pri multi-selectu ty vybrany moznosti na jednom radku? Nebo by se to melo natahovat do vysky? M.

**Comment by jzelenka** [comment]
Jak je to ted je docela dobry - vybrany moznosti se pridavaji vedle sebe na jeden radek, ale kdyz se pak nevejdou, tak si zacnou druhy radek a policko se roztahne na vysku...

![image](https://cloud.githubusercontent.com/assets/1957955/10389143/a24ca326-6e6f-11e5-968b-8a0d1426fe7b.png)

**Comment by martinnemec3** [comment]
V tom pripade ale tu min-height: 48px musim nechat. Aby to
* bylo roztahovatelne
* defaultne melo 48px, stejne jako to ma TextField

**Comment by martinnemec3** [comment]
Kdyz to budes chtit mensi, tak si ji prekrejes (tak jako prekryjes klasickou height, kdyz chces mensi TextField)

**Comment by jzelenka** [comment]
dobre, jestli se to chova stejne jako TextField tak asi dobry - kolem neho to vsechno stavime....
pripadne se ozvu se az na to narazim...

Napis prosim do te komponenty nejakou dokumentaci o tomto...

**Comment by martinnemec3** [comment]
Komponenta je teda pripravena, kdyz by bylo potreba neco doplnit, nebo bys narazil na neco neocekavanyho v chovani, tak napis. Vyresil jsem i tu modrou linku u multi.

**Comment by jzelenka** [comment]
super,
mrkni jeste prosim v masteru v styledSelect.less na .Select-control

byly tam nejake konflikty, jestli jsem to dobre zmergoval...

**Comment by martinnemec3** [comment]
Vypada to, ze to je ok.
